openapi: "3.1.0"
info:
  title: An API
  version: "1.0"
components:
  schemas:
    SchemaBoolean:
      type: boolean
    SchemaObject:
      properties:
        aBooleanProperty:
          type: boolean